version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "tschaffter"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "tschaffter"