version: "3.8"

services:
  date-annotator:
    image: nlpsandbox/date-annotator-example:1.0.1
    container_name: date-annotator
    restart: always
    networks:
      - nlp-sandbox-internal

  person-name-annotator:
    image: nlpsandbox/person-name-annotator-example:1.0.1
    container_name: person-name-annotator
    restart: always
    networks:
      - nlp-sandbox-internal

  physical-address-annotator:
    image: nlpsandbox/physical-address-annotator-example:1.0.1
    container_name: physical-address-annotator
    restart: always
    networks:
      - nlp-sandbox-internal

  phi-deidentifier:
    image: nlpsandbox/phi-deidentifier:edge
    build:
      context: server
      dockerfile: Dockerfile
    container_name: phi-deidentifier
    restart: always
    environment:
      - DATE_ANNOTATOR_HOST=date-annotator
      - DATE_ANNOTATOR_PORT=8080
      - PERSON_NAME_ANNOTATOR_HOST=person-name-annotator
      - PERSON_NAME_ANNOTATOR_PORT=8080
      - PHYSICAL_ADDRESS_ANNOTATOR_HOST=physical-address-annotator
      - PHYSICAL_ADDRESS_ANNOTATOR_PORT=8080
    networks:
      - nlp-sandbox-internal
      - nlp-sandbox
    ports:
      - "80:8080"
    depends_on:
      - date-annotator
      - person-name-annotator
      - physical-address-annotator

networks:
  nlp-sandbox:
  nlp-sandbox-internal:
    internal: true